eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.2.176:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8804
spring:
  application:
    name: service-inventory
  zipkin:
    base-url: http://172.16.2.176:9411
    